services:
  server:
    image: ghcr.io/0ximjosh/tetris-server:latest
    build:
      context: .
      platforms:
        - linux/amd64
        - linux/arm64
    env_file: .env
    command: --host ${HOST:-localhost} --port ${PORT:-2222}
    restart: always
    ports:
      - 22:22
